language: objective-c
osx_image: xcode9.2

env:
  global:
  - IOS_FRAMEWORK_SCHEME="MDBProvider"
  - WORKSPACE="InCinema.xcworkspace"
  matrix:
  - DESTINATION="OS=12.0,name=iPhone 6"   SCHEME="$IOS_FRAMEWORK_SCHEME"     ACTION="build test"

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pip install --user codecov

script:
  - set -o pipefail
  - xcodebuild -scheme "$SCHEME" -workspace "$WORKSPACE" -destination "$DESTINATION" clean $ACTION | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
